#+TITLE:XenHunt Config (org)
#+AUTHOR: Evgeny Berlizov (XenHunt)
#+DESCRIPTION: XenHunt's config of org
#+STARTUP: content
#+PROPERTY: header-args :tangle org-mine.el

* Содержание
:PROPERTIES:
:TOC:      :include all :depth 100 :force (nothing) :ignore (this) :local (nothing)
:END:
:CONTENTS:
- [[#введение][Введение]]
- [[#fast-loading][Fast-Loading]]
- [[#org-mode][Org-Mode]]
  - [[#ret---open-link-or-exec-src-block][RET - open link or exec src block]]
  - [[#auto-fill-mode][Auto-Fill-Mode]]
  - [[#hover-links][Hover Links]]
  - [[#org-custom-todos][Org Custom TODOS]]
  - [[#org-inline-images][Org Inline Images]]
  - [[#org-appear][Org-Appear]]
  - [[#toc][Toc]]
  - [[#highlight-todo][Highlight TODO]]
  - [[#org-bullets][Org-Bullets]]
  - [[#org-modern][Org-Modern]]
  - [[#org-modern-indent][Org-Modern-Indent]]
  - [[#org-tempo][Org Tempo]]
  - [[#org-headings-size][Org Headings Size]]
  - [[#org-auto-tangle][Org-Auto-Tangle]]
  - [[#org-detangle-fix][Org-Detangle-Fix]]
  - [[#org-fragtog][Org-Fragtog]]
  - [[#org-latex-impatient][Org-LaTeX-Impatient]]
  - [[#ob-async][OB-Async]]
  - [[#ob-mermaid][OB-Mermaid]]
  - [[#chatu][Chatu]]
  - [[#org-babel-load-languages][ORG-Babel-Load-Languages]]
  - [[#org-download][Org-Download]]
  - [[#org-ref][Org-Ref]]
  - [[#corg][Corg]]
  - [[#verb][Verb]]
  - [[#org-sticky-header][Org-Sticky-Header]]
  - [[#org-transclusion][Org-Transclusion]]
  - [[#org-tag-beautify][Org-Tag-Beautify]]
  - [[#раскладка][Раскладка]]
    - [[#agenda][Agenda]]
- [[#provide][Provide]]
:END:

* Введение
:PROPERTIES:
:CUSTOM_ID: введение
:END:

Эта часть конфига посвящена настройке =org-mode= в =Emacs=.

* Fast-Loading
:PROPERTIES:
:CUSTOM_ID: fast-loading
:END:

Быстрая загрузка модуля.

#+begin_src emacs-lisp
;; -*- lexical-binding: t;  no-byte-compile: t -*-
#+end_src

* Org-Mode
:PROPERTIES:
:CUSTOM_ID: org-mode
:END:

#+begin_src emacs-lisp
;; (use-package org-mode
;;   :ensure nil
;;   :config
  ;; (require 'org-crypt)
;;   (org-crypt-use-before-save-magic)
;;   (setq org-tags-exclude-from-inheritance '("crypt")))
(use-package org
  :ensure nil
  :custom
  (org-capture-bookmark nil "Отключаем закладку в org-capture")
  :hook
  (org-mode . (lambda ()
                (setq-local org-preview-latex-image-directory (get-cache-path "images/" t)))))
#+end_src

#+RESULTS:
: t

** RET - open link or exec src block
:PROPERTIES:
:CUSTOM_ID: ret---open-link-or-exec-src-block
:END:

Мое решение (и =gptel=) для объединения открытия ссылки или запуска src block'а в Emacs одно клавишой =RET=.

#+begin_src emacs-lisp

(defun my/org-babel-execute-maybe ()
  "If point is at a source code block, execute it with org-babel."
  (interactive)
  (require 'org)
  (let ((context (org-element-context)))
    (when (and context
               (eq (car context) 'src-block))
      (org-babel-execute-src-block))))

(defun my/org-link-maybe ()
  "If point is at an org-mode link, open it."
  (interactive)
  (require 'org)
  (let ((context (org-element-context)))
    (when (and context
               (eq (car context) 'link)
               ;; Ensure the link is not part of a src-block
               (not (eq (org-element-property :parent context) 'src-block)))
      (org-open-at-point))))

(defun my/org-dynamic-block-maybe ()
  "Update org dynamic block if point is at a line starting with #+BEGIN:."
  (interactive)
  (require 'org)
  (save-excursion
    (beginning-of-line)
    (when (looking-at-p "^\\s-*#\\+BEGIN:")
      (org-update-dblock))))
(defun my/ret-keybindings ()
  "It combines my maybe commands together."
  (interactive)
  (my/org-babel-execute-maybe)
  (my/org-link-maybe)
  (my/org-dynamic-block-maybe))

(evil-define-key 'normal org-mode-map (kbd "RET") 'my/ret-keybindings)
;; (add-hook 'org-mode-hook #'auto-fill-mode)
;; (setq org-agenda-files '("~/.org/roam/2024-08-28-22:33:31-список.org"))
#+end_src

#+RESULTS:
** Auto-Fill-Mode
:PROPERTIES:
:CUSTOM_ID: auto-fill-mode
:END:
#+begin_src emacs-lisp
;; (use-package visual-fill-column
;;   ;; :hook
;;   ;; (org-mode visual-line)
;;   :init
;;   (add-hook 'visual-line-mode-hook #'visual-fill-column-for-vline))
(add-hook 'org-mode-hook #'visual-line-mode)
#+end_src
** Hover Links 
:PROPERTIES:
:CUSTOM_ID: hover-links
:END:
#+begin_src emacs-lisp
(setq org-mouse-1-follows-link t)
(setq org-descriptive-links t)
#+end_src

** Org Custom TODOS
:PROPERTIES:
:CUSTOM_ID: org-custom-todos
:END:
#+begin_src emacs-lisp
(setq-default org-todo-keywords '((sequence "TODO" "DONE")
                                  (sequence "TODO-READING" "READING" "|" "FINISHED-READING")))
#+end_src

** Org Inline Images
:PROPERTIES:
:CUSTOM_ID: org-inline-images
:END:
#+begin_src  emacs-lisp
(setq org-startup-with-inline-images t)
#+end_src

#+RESULTS:
: t

** Org-Appear 
:PROPERTIES:
:CUSTOM_ID: org-appear
:END:

=org-appear= - это пакет, позволяющий динамически скрывать/показывать специальные конструкции, такие как *выделение*, /курсив/, =хорошее выделение=, _подчеркивание_, [[ссылки]].

#+begin_src emacs-lisp
(use-package org-appear
  :defer 1
  :custom
  (org-appear-autoemphasis t)
  (org-appear-autolinks t)
  (org-appear-autosubmarkers t)
  (org-appear-autoentities t)
  (org-appear-autokeywords t)
  :config
  (add-hook 'org-mode-hook 'org-appear-mode)
  (setq org-appear-trigger 'manual)
  (add-hook 'org-mode-hook (lambda ()
                             (add-hook 'evil-insert-state-entry-hook
                                       #'org-appear-manual-start
                                       nil
                                       t)
                             (add-hook 'evil-insert-state-exit-hook
                                       #'org-appear-manual-stop
                                       nil
                                       t)))
  )
#+end_src
** Toc
:PROPERTIES:
:CUSTOM_ID: toc
:END:

=org-make-toc= - пакет для удобного добавления TOC - Table Of Content, оглавления в =org= файлах.

#+begin_src emacs-lisp
(use-package org-make-toc
  :defer 2
  :config
  (setq org-make-toc-insert-custom-ids t)
  (add-hook 'org-mode-hook #'org-make-toc-mode)
  (my/set-fonts)
  )
(elpaca-wait)
#+end_src
** Highlight TODO 
:PROPERTIES:
:CUSTOM_ID: highlight-todo
:END:

=hl-todo= - подсветка TODO и иже подобные вещи в =org=.

#+begin_src emacs-lisp
(use-package hl-todo
  :ensure (:depth nil)
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("TODO-READING" warning bold)
          ("READING" font-lock-keyword-face bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("FINISHED-READING" success bold)
          ("DONE" success bold)
          ("DEPRECATED" font-lock-doc-face bold))))

(use-package consult-todo
  :after (consult hl-todo))
#+end_src
** Org-Bullets
:PROPERTIES:
:CUSTOM_ID: org-bullets
:END:

=org-bullets= - это пакет, меняющий заголовки и превращающий их в нечто более красивое.

#+begin_src emacs-lisp
(setq org-startup-indented nil
      org-pretty-entities t)
;; (use-package org-bullets
;;   :config
;;   (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
(elpaca-wait)
#+end_src

#+RESULTS:

** Org-Modern
:PROPERTIES:
:CUSTOM_ID: org-modern
:END:
#+begin_src emacs-lisp
(use-package org-modern
  :hook (org-mode . org-modern-mode)
  :custom
  ;; (org-modern-hide-stars " ")		; adds extra indentation
  ;; (org-modern-table nil)
  (org-modern-list 
   '(;; (?- . "-")
     (?* . "•")
     (?+ . "‣")))
  (org-modern-block-name '("" . "")) ; or other chars; so top bracket is drawn promptly
  ;; (org-modern-fold-stars
  ;;  '(("◉" . "◯")
  ;;    ("│" . "└")
  ;;    (" │" . " └")
  ;;    (" │" . " └")))
  )
#+end_src

#+RESULTS:
: [nil 26321 35790 743497 nil elpaca-process-queues nil nil 928000 nil]

** Org-Modern-Indent
:PROPERTIES:
:CUSTOM_ID: org-modern-indent
:END:

=org-modern-indent= добавляет красивое выделение для блоков в =org=.

#+begin_src emacs-lisp
(use-package org-modern-indent
  :ensure (:host github :repo "jdtsmith/org-modern-indent")
  :after org-modern
  :config
  (add-hook 'org-mode-hook #'org-modern-indent-mode 90)
  )
#+end_src

#+RESULTS:
: [nil 26321 37179 983531 nil elpaca-process-queues nil nil 850000 nil]

** Org Tempo 
:PROPERTIES:
:CUSTOM_ID: org-tempo
:END:

#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("sq" . "src sql"))
#+end_src

#+RESULTS:
: ((sq . src sql) (py . src python) (el . src emacs-lisp) (a . export ascii) (c . center) (C . comment) (e . example) (E . export) (h . export html) (l . export latex) (q . quote) (s . src) (v . verse))

** Org Headings Size 
:PROPERTIES:
:CUSTOM_ID: org-headings-size
:END:
#+begin_src emacs-lisp
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.7))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.4))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.3))))
 '(org-level-6 ((t (:inherit outline-5 :height 1.2))))
 '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
#+end_src

** Org-Auto-Tangle 
:PROPERTIES:
:CUSTOM_ID: org-auto-tangle
:END:

=org-auto-tangle= - это пакет, позволяющий автоматически при сохранении =org= файла импортировать весь код из блоков в файлы.

#+begin_src emacs-lisp
(use-package org-auto-tangle
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))
#+end_src

** Org-Detangle-Fix
:PROPERTIES:
:CUSTOM_ID: org-detangle-fix
:END:

Меня очень раздражает, что при вызове =org-babel-detangle= открывается
org файл, где находится tangled src blocks. К счастью, я нашел
решение:
#+begin_src emacs-lisp
(defun org-babel-detangle-no-buffer-pop-up (orig-fun &rest args)
  (save-excursion
    (let ((display-buffer-alist
           '((".*" (display-buffer-no-window) (allow-no-window . t)))))
      (apply orig-fun args))))

(advice-add 'org-babel-detangle :around #'org-babel-detangle-no-buffer-pop-up)
#+end_src

** Org-Fragtog
:PROPERTIES:
:CUSTOM_ID: org-fragtog
:END:

=org-fragtog= - это пакет похожий на =org-appear=, но для =LaTex= функций и конструкций. 

#+begin_src emacs-lisp 
(use-package org-fragtog
:after org
:hook (org-mode . org-fragtog-mode) ; this auto-enables it when you enter an org-buffer, remove if you do not want this
:config
;; whatever you want
)
#+end_src

** Org-LaTeX-Impatient
:PROPERTIES:
:CUSTOM_ID: org-latex-impatient
:END:
#+begin_src emacs-lisp
;; (use-package org-latex-impatient
;;   :defer t
;;   :hook (org-mode . org-latex-impatient-mode)
;;   :init
;;   (setq org-latex-impatient-tex2svg-bin
;;         ;; location of tex2svg executable
;;         "/home/berlizoves/.config/nvm/versions/node/v22.18.0/bin/tex2svg"))
#+end_src

** OB-Async
:PROPERTIES:
:CUSTOM_ID: ob-async
:END:

=ob-async= - асинхронное выполнение src блоков в =org=.

#+begin_src emacs-lisp
(use-package ob-async
  :config

(setq ob-async-no-async-languages-alist '("jupyter-python" "jupyter-julia" "jupyter-R"))
)
#+end_src

** OB-Mermaid
:PROPERTIES:
:CUSTOM_ID: ob-mermaid
:END:
#+begin_src emacs-lisp
(use-package ob-mermaid)
(elpaca-wait)
#+end_src

#+RESULTS:
: [nil 26520 35704 297318 nil elpaca-process-queues nil nil 316000 nil]

** Chatu
:PROPERTIES:
:CUSTOM_ID: chatu
:END:
#+begin_src emacs-lisp
(use-package chatu
  :ensure (chatu :host github :type git :repo "XenHunt/chatu" :branch "chatu-skip-lines-fix" 
                 :files ("*.el" "*.el.in" "dir" "*.info"
                         "*.texi" "*.texinfo" "doc/dir"
                         "doc/*.info" "doc/*.texi"
                         "doc/*.texinfo" "lisp/*.el" "docs/dir"
                         "docs/*.info" "docs/*.texi"
                         "docs/*.texinfo" (:exclude
                                           ".dir-locals.el" "test.el" "tests.el"
                                           "*-test.el" "*-tests.el" "LICENSE"
                                           "README*" "*-pkg.el"))
                 )
  :hook ((org-mode markdown-mode) . chatu-mode)
  (chatu-mode . (lambda ()
                  (setq-local chatu-input-dir (get-cache-path "draws" t))
                  (setq-local chatu-output-dir (get-cache-path "images" t))))
  :commands (chatu-add
             chatu-open))
(use-package consult-chatu              ;
  :ensure (consult-chatu :host github :type git :repo "XenHunt/consult-chatu" :branch "master" files ("*.el") :protocol ssh))

(elpaca-wait)
#+end_src

#+RESULTS:
: [nil 26891 26806 68629 nil elpaca-process-queues nil nil 883000 nil]

** ORG-Babel-Load-Languages 
:PROPERTIES:
:CUSTOM_ID: org-babel-load-languages
:END:
#+begin_src emacs-lisp
(setq org-src-fontify-natively t)
(setq org-confirm-babel-evaluate nil)
(require 'ob-clojure)
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (shell . t)
   (mermaid . t)
   (clojure . t)
   (python . t)
   ;; (jupyter . t)
   ))

#+end_src

#+RESULTS:

** Org-Download 
:PROPERTIES:
:CUSTOM_ID: org-download
:END:

=org-download= - drag-and-drop для =org=.

#+begin_src emacs-lisp
(use-package org-download
  :defer 4
  :hook ((org-mode dired-mode) . (lambda ()
            (setq-local org-download-image-dir (get-cache-path "images" t))))
  :config
  (add-hook 'dired-mode-hook 'org-download-enable)
  )
#+end_src

** Org-Ref
:PROPERTIES:
:CUSTOM_ID: org-ref
:END:

=org-ref= позволяет создавать цитаты, кросреференсы, индексы и глоссарии как ссылку в =org=.

:PROPERTIES:
:CUSTOM_ID: org-ref
:END:
#+begin_src emacs-lisp
;; (use-package org-ref
;; :no-require t)

#+end_src
** Corg
:PROPERTIES:
:CUSTOM_ID: corg
:END:

=corg= добавляет автоподстановку в src блоки и им подобные.

#+begin_src emacs-lisp
(use-package corg
  :ensure (:host github :repo "isamert/corg.el"))
#+end_src
** Verb
:PROPERTIES:
:CUSTOM_ID: verb
:END:

Обычный REST клиент при помощи =org=.

#+begin_src emacs-lisp
(use-package verb
  :defer 5
  :after org
  :config
  ;; (verb-util--log)
)
#+end_src
** Org-Sticky-Header
:PROPERTIES:
:CUSTOM_ID: org-sticky-header
:END:
#+begin_src emacs-lisp
(use-package org-sticky-header
  :hook (org-mode . org-sticky-header-mode))
#+end_src

#+RESULTS:
: [nil 26461 11419 612426 nil elpaca-process-queues nil nil 791000 nil]
** Org-Transclusion
:PROPERTIES:
:CUSTOM_ID: org-transclusion
:END:
#+begin_src emacs-lisp
(use-package org-transclusion
  :after org
  :hook (org-mode . org-transclusion-mode)
  :init
  )
#+end_src

#+RESULTS:
: [nil 26321 40045 673291 nil elpaca-process-queues nil nil 408000 nil]
** Org-Tag-Beautify
:PROPERTIES:
:CUSTOM_ID: org-tag-beautify
:END:
#+begin_src emacs-lisp
;; (use-package org-tag-beautify
;;   :ensure t
;;   :custom (org-tag-beautify-data-dir "~/.emacs.d/.cache/org-tag-beautify/data/")
;;   :init (org-tag-beautify-mode 1))
#+end_src
** Раскладка
:PROPERTIES:
:CUSTOM_ID: раскладка
:END:
[[https://github.com/doomemacs/doomemacs/blob/master/modules/lang/org/config.el][Doom-Config Org-Mode]]

#+begin_src emacs-lisp
(general-define-key
 :states 'normal
 :keymaps 'org-mode-map
 :prefix "]"
 "h" 'org-next-visible-heading
 )

(general-define-key
 :states 'normal
 :keymaps 'org-mode-map
 :prefix "["
 "h" 'org-previous-visible-heading
 )

(general-define-key
 :states 'normal
 :keymaps 'org-mode-map
 :prefix "SPC"

 "m #" 'org-update-statistics-cookies
 "m '" 'org-edit-special
 "m *" 'org-ctrl-c-star
 "m +" 'org-ctrl-c-minus
 "m ," 'org-switchb
 "m ." 'org-goto
 "m @" 'org-cite-insert
 "m ." 'consult-org-heading
 "m /" 'consult-org-agenda
 "m A" 'org-archive-subtree-default
 "m e" 'org-export-dispatch
 "m E" 'org-emphasize
 "m f" 'org-footnote-action
 "m h" 'org-toggle-heading
 "m i" 'org-toggle-item
 "m I" 'org-id-get-create
 "m k" 'org-babel-remove-result
 "m n" 'org-store-link
 "m o" 'org-set-property
 "m q" 'org-set-tags-command
 "m t" 'org-todo
 "m T" 'org-todo-list
 "m x" 'org-toggle-checkbox
 
 ;; Attachments
 "m a a" 'org-attach
 "m a d" 'org-attach-delete-one
 "m a D" 'org-attach-delete-all
 "m a n" 'org-attach-new
 "m a o" 'org-attach-open
 "m a O" 'org-attach-open-in-emacs
 "m a r" 'org-attach-reveal
 "m a R" 'org-attach-reveal-in-emacs
 "m a u" 'org-attach-url
 "m a s" 'org-attach-set-directory
 "m a S" 'org-attach-sync
 "m a c" 'org-download-screenshot
 "m a p" 'org-download-clipboard
 "m a P" 'org-download-yank

 ;; Transclusion
 "m a t t" 'org-transclusion-make-from-link
 "m a t a" 'org-transclusion-add
 "m a t A" 'org-transclusion-add-all
 "m a t r" 'org-transclusion-remove
 "m a t d" 'org-transclusion-detach
 "m a t l" 'org-transclusion-live-sync-start
 "m a t L" 'org-transclusion-live-sync-exit
 "m a t o" 'org-transclusion-open-source
 
 ;; Tables
 "m b -" 'org-table-insert-hline
 "m b a" 'org-table-align
 "m b b" 'org-table-blank-field
 "m b e" 'org-table-edit-field
 "m b f" 'org-table-edit-formulas
 "m b h" 'org-table-field-info
 "m b s" 'org-table-sort-lines
 "m b r" 'org-table-recalculate
 "m b R" 'org-table-recalculate-buffer-tables
 "m b d c" 'org-table-delete-column
 "m b d r" 'org-table-kill-row
 "m b i c" 'org-table-insert-column
 "m b i h" 'org-table-insert-hline
 "m b i r" 'org-table-insert-row
 "m b i H" 'org-table-hline-and-move
 "m b t f" 'org-table-toggle-formula-debugger
 "m b t o" 'org-table-toggle-coordinate-overlays

 ;; Clock
 "m c c" 'org-clock-cancel
 "m c d" 'org-clock-mark-default-task
 "m c e" 'org-clock-modify-effort-estimate
 "m c E" 'org-set-effort
 "m c g" 'org-clock-goto
 "m c i" 'org-clock-in
 "m c I" 'org-clock-in-last
 "m c o" 'org-clock-out
 "m c r" 'org-clock-resolve-clock
 "m c R" 'org-clock-report
 "m c t" 'org-evaluate-time-range
 "m c =" 'org-clock-timestamps-up
 "m c -" 'org-clock-timestamps-down

 ;; Dates
 "m d d" 'org-deadline
 "m d s" 'org-schedule
 "m d t" 'org-time-stamp
 "m d T" 'org-time-stamp-inactive

 ;; Goto
 "m g g" 'consult-org-heading
 "m g G" 'consult-org-agenda
 "m g c" 'org-clock-goto
 "m g i" 'org-id-goto
 "m g r" 'org-refile-goto-last-stored
 "m g x" 'org-capture-goto-last-stored

 ;; Links
 "m l i" 'org-id-store-link
 "m l l" 'org-insert-link
 "m l L" 'org-insert-all-links
 "m l s" 'org-store-link
 "m l S" 'org-insert-last-stored-link
 "m l t" 'org-toggle-link-display

 ;; Publish (Зачем это надо - непонятно)

 "m P a" 'org-publish-all
 "m P f" 'org-publish-current-file
 "m P p" 'org-publish
 "m P P" 'org-publish-current-project
 "m P s" 'org-publish-sitemap

 ;; Priority
 "m p d" 'org-priority-down
 "m p p" 'org-priority
 "m p u" 'org-priority-up

 ;; Tree/Subtree

 "m s a" 'org-toggle-archive-tag
 "m s b" 'org-tree-to-indirect-buffer
 "m s c" 'org-clone-subtree-with-time-shift
 "m s d" 'org-cut-subtree
 "m s h" 'org-promote-subtree
 "m s j" 'org-move-subtree-down
 "m s k" 'org-move-subtree-up
 "m s l" 'org-demote-subtree
 "m s n" 'org-narrow-to-subtree
 "m s r" 'org-refile
 "m s s" 'org-sparse-tree
 "m s A" 'org-archive-subtree-default
 "m s N" 'widen
 "m s S" 'org-sort
 
 ;; Chatu
 "m a c" 'consult-chatu-new
 )

(leader-key
  "n" '(my/org-roam-tmenu :wk "Note menu"))


;; (general-def 'normal 'override "C-x C-x" """)
#+end_src
*** Agenda
:PROPERTIES:
:CUSTOM_ID: agenda
:END:
#+begin_src emacs-lisp
(general-def
 :states 'normal
 :keymaps 'org-agenda-mode-map
 :prefix "SPC m"
 
 "q" 'org-agenda-set-tags
 "r" 'org-agenda-refile
 "t" 'org-agenda-todo
 
 ;; Date
 "d d" 'org-agenda-deadline
 "d s" 'org-agenda-schedule

 ;; Clock
 "c c" 'org-agenda-clock-cancel
 "c g" 'org-agenda-clock-goto
 "c i" 'org-agenda-clock-in
 "c o" 'org-agenda-clock-out
 "c r" 'org-agenda-clockreport-mode
 "c s" 'org-agenda-show-clocking-issues

 ;;Priority
 "p d" 'org-agenda-priority-down
 "p p" 'org-agenda-priority
 "p u" 'org-agenda-priority-up
)
#+end_src

* Provide
:PROPERTIES:
:CUSTOM_ID: provide
:END:
#+begin_src emacs-lisp
(provide 'org-mine)
#+end_src
