#+TITLE:XenHunt Config (full)
#+AUTHOR: Evgeny Berlizov (XenHunt)
#+DESCRIPTION: XenHunt's full config loading
#+STARTUP: content
#+PROPERTY: header-args :tangle full.el
* Содержание
:PROPERTIES:
:TOC:      :include all :depth 100 :force (nothing) :ignore (this) :local (nothing)
:END:
:CONTENTS:
- [[#введение][Введение]]
- [[#fast-loading][Fast-Loading]]
- [[#загрузка-конфига][Загрузка конфига]]
  - [[#загрузка-скриптов][Загрузка скриптов]]
  - [[#base][Base]]
  - [[#custom][Custom]]
  - [[#org][Org]]
  - [[#other][Other]]
  - [[#programming][Programming]]
  - [[#ai][AI]]
  - [[#usb][USB]]
  - [[#telega][Telega]]
  - [[#irc][IRC]]
  - [[#elfeed][Elfeed]]
- [[#provide][Provide]]
:END:

* Введение
:PROPERTIES:
:CUSTOM_ID: введение
:END:

Эта часть конфига объединяет все модули в один обший конфиг.

* Fast-Loading
:PROPERTIES:
:CUSTOM_ID: fast-loading
:END:

Быстрая загрузка модуля.

#+begin_src emacs-lisp
;; -*- lexical-binding: t;  no-byte-compile: t -*-
#+end_src

* Загрузка конфига
:PROPERTIES:
:CUSTOM_ID: загрузка-конфига
:END:

Загрузка всего конфига.

** Загрузка скриптов
:PROPERTIES:
:CUSTOM_ID: загрузка-скриптов
:END:

Загрузка базовых скриптов.

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/scripts/")
(require 'scripts)
#+end_src
** Base
:PROPERTIES:
:CUSTOM_ID: base
:END:

Это базовая часть конфига, включающая в себя самые базовые вещи (evil-mode, значения по-умолчанию и некоторые другие вещи). Подробнее: [[./base/README.org][README базы]]
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/base/")
(require 'base)
#+end_src
** Custom
:PROPERTIES:
:CUSTOM_ID: custom
:END:

Эта часть конфига посвященая всяким украшательствам (тема, фонты и другое). Подробнее: [[./custom/README.org][README кастомизации]]
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/custom/")
(require 'beauty)
#+end_src
** Org
:PROPERTIES:
:CUSTOM_ID: org
:END:

Эта часть посвящена всем расширениям для =org-mode=. Подробнее: [[./org/README.org][README для org]]

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/org/")
(require 'org-mine)
#+end_src
** Other
:PROPERTIES:
:CUSTOM_ID: other
:END:

Эта часть посвящена разнообразным вещам, которые не могут быть отнесены к другим модулям. Подробнее: [[./other/README.org][README оставшихся вещей]]

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/other/")
(require 'other)
#+end_src
** Programming
:PROPERTIES:
:CUSTOM_ID: programming
:END:

Эта часть посвящена всему, что превращает =Emacs= в IDE (lsp, дебаг и т.д.). Подробнее: [[./programming/README.org][README для программирования]]

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/programming/")
(require 'programming)
#+end_src
** AI
:PROPERTIES:
:CUSTOM_ID: ai
:END:

Эта часть посвящена добавлению ИИ (=Codeium= и =gptel=) в =Emacs=. Подробнее: [[./ai/README.org][README для ИИ]]

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/ai/")
(require 'ai)
#+end_src
** USB
:PROPERTIES:
:CUSTOM_ID: usb
:END:

Эта часть подключает =usb-wofi-mount= - скрипт для подключения usb девайсов в мою систему горячиъ клваши в Emacs. Подробнее: [[./usb-mount/README.org][README для usb]], [[https://github.com/luyves/polybar-rofi-usb-mount/blob/master/rofi-usb-mount.sh][Ссылка на оригинальный скрипт (вместо rofi надо замсенить на wofi и все будет работать)]].
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/telega/")
(require 'telega-package)
#+end_src
** Telega
:PROPERTIES:
:CUSTOM_ID: telega
:END:

Эта часть подключает =telega=. Подробнее: [[./telega/README.org][README для telega]].
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/telega/")
(require 'telega-package)
#+end_src
** IRC
:PROPERTIES:
:CUSTOM_ID: irc
:END:

Эта часть подключает =irc= клиент - =cicer=. Подробнее: [[./irc/README.org][README для cicer]].
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/irc/")
(require 'irc-package)
#+end_src
** Elfeed
:PROPERTIES:
:CUSTOM_ID: elfeed
:END:

Эта часть подключает =RSS= клиент - =elfeed=. Подробнее: [[./elfeed/README.org][README для elfeed]].
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/lisp/conf-files/elfeed/")
(require 'elfeed-package)
#+end_src

#+RESULTS:
: elfeed-package

* Provide
:PROPERTIES:
:CUSTOM_ID: provide
:END:

Тут просто предоставляю =Emacs= доступ к конфигу.

#+begin_src emacs-lisp
(provide 'full)
#+end_src
